apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf-client
  labels:
    environment: iperf-client_tester
    app: iperf-client
  annotations:
    k8s.v1.cni.cncf.io/networks: sriov-direct
spec:
  replicas: 3
  selector:
    matchLabels:
      environment: iperf-client_tester
      app: iperf-client
  template:
    metadata:
      labels:
        environment: iperf-client_tester
        app: iperf-client
      annotations:
        k8s.v1.cni.cncf.io/networks: sriov-direct
    spec:
      nodeName: wrk-np-q2fhg-5587ccf57fxxpfj9-fpjlr
      containers:
      - name: iperf-client
        command: ["/bin/bash", "-c", "PID=; trap 'kill $PID' TERM INT; sleep infinity & PID=$!; wait $PID"]
        image: airgap.vmvo.registry.vf/registry/spyroot/pktgen_toolbox_generic
        imagePullPolicy: IfNotPresent
        securityContext:
          capabilities:
            add: ["IPC_LOCK", "NET_ADMIN", "SYS_TIME", "CAP_NET_RAW", "CAP_BPF", "CAP_SYS_ADMIN", "SYS_ADMIN"]
          privileged: true
        env:
          - name: PATH
            value: "/bin:/sbin:/usr/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:$PATH"
        volumeMounts:
        - name: sys
          mountPath: /sys
          readOnly: true
        - name: modules
          mountPath: /lib/modules
          readOnly: true
        resources:
          requests:
            cpu: "8"
            intel.com/sriov-direct: '1'
            memory: 8Gi
          limits:
            cpu: "8"
            intel.com/sriov-direct: '1'
            memory: 8Gi
      volumes:
      - name: sys
        hostPath:
          path: /sys
      - name: modules
        hostPath:
          path: /lib/modules
      nodeSelector:
        kubernetes.io/os: linux