apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpdkpod
  labels:
    environment: dpdk_tester
    app: dpdkpod
spec:
  replicas: 2
  selector:
    matchLabels:
      environment: dpdk_tester
      app: dpdkpod
  template:
    metadata:
      labels:
        environment: dpdk_tester
        app: dpdkpod
    spec:
      containers:
      - name: dpdkpod
        command: ["/bin/bash", "-c", "PID=; trap 'kill $PID' TERM INT; sleep infinity & PID=$!; wait $PID"]
        image: airgap.vmvo.registry.vf/registry/spyroot/dpdk_tester
        imagePullPolicy: Always
        securityContext:
          capabilities:
            add: ["IPC_LOCK", "NET_ADMIN", "SYS_TIME", "CAP_NET_RAW", "CAP_BPF", "CAP_SYS_ADMIN", "SYS_ADMIN"]
          privileged: true
        env:
          - name: PATH
            value: "/bin:/sbin:/usr/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:$PATH"
        volumeMounts:
        - name: sys
          mountPath: /sys
          readOnly: true
        - name: modules
          mountPath: /lib/modules
          readOnly: true
        resources:
          requests:
            memory: 2Gi
            cpu: "2"
            intel.com/sriovdpdk: '1'
          limits:
            hugepages-1Gi: 2Gi
            cpu: "2"
            intel.com/sriovdpdk: '1'
      volumes:
      - name: sys
        hostPath:
          path: /sys
      - name: modules
        hostPath:
          path: /lib/modules
      nodeSelector:
        kubernetes.io/os: linux

