---                     
#Task 
  - hosts: leaf
    vars:
      nxos_provider:
        username: "{{ user }}"
        password: "{{ pwd }}"
        transport: nxapi
        host: "{{ inventory_hostname }}"
    tasks:
      - include: enable_nxosapi.yml
