- name: NXOS Query
  hosts: leaf
  connection: local

  tasks:
  - name: Enable nx-api
    vars:
      # ansible_connection: network_cli
      # ansible_network_os: nxos
      ansible_user: "admin"
      ansible_password: "VMware1!"
      ansible_connection: ansible.netcommon.network_cli
      ansible_network_os: cisco.nxos.nxos
      ansible_become: yes
      ansible_become_method: enable
      ansible_become_password: VMware1!
      ansible_ssh_pass: VMware1!
      
      nxos_provider:
        username: "{{ user }}"
        password: "{{ pwd }}"
        transport: nxapi
        host: "{{ inventory_hostname }}"

    nxos_nxapi:
        enable_http: yes
        enable_https: yes
      