- name: Create a login user
  user:
    name: "vmware"
    password: "{{ VMware1! | password_hash('sha512') }}"
    groups:
      - root
    state: present

- name: Install a list of packages.
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - curl
    - wget