- name: Create a login user
  user:
    name: "vmware"
    password: "VMware1!"
    groups:
      - root
    state: present

- name: Install packages on Toolbox VM
  yum:
    name: 
      - curl
      - epel-release
      - wget
      - powershell
      - kubectl
    state: present
