# Playbook create ASOCS stack.
#
#  - It populate all DVS.
#  - Create required Port-groups on separate DVS, dedicated for all SRIOV.
#  - Take reference OVA , upload as master template.
#  - Re-create two template , each template for CU and DU.
#  - Create new network adapters and maps each to SRIOV.
#  - Serialize back all VM as templates.
#
# In case of issue mbayramo@vmware.com

# First we get all DVS.
- name: Gather all registered dvswitch
  community.vmware.vmware_dvswitch_info:
    hostname: "{{ vc_name }}"
    username: "{{ vc_user }}"
    password: "{{ vc_pass }}"
    validate_certs: False
  delegate_to: localhost
  register: dvswitch_info

# Now we can Upload ova and convert to template.
- name: "Deploy OVF template"
  community.vmware.vmware_deploy_ovf:
    allow_duplicates: False
    validate_certs: False
    hostname: "{{ vc_name }}"
    username: "{{ vc_user }}"
    password: "{{ vc_pass }}"
    datacenter: "{{ dc }}"
    cluster: "{{ cluster_name }}"
    datastore: "{{ datast }}"
    name: druid_centos_template
    power_on: no
    ovf: "{{ centos_ova }}"
  delegate_to: localhost