- name: Gather all registered dvswitch
  community.vmware.vmware_dvswitch_info:
    hostname: "{{ vc_name }}"
    username: "{{ vc_user }}"
    password: "{{ vc_pass }}"
    validate_certs: False
  delegate_to: localhost
  register: dvswitch_info

# Upload ova and convert to template
- name: Deploy vRealize Orchestrator
  community.vmware.vmware_deploy_ovf:
    allow_duplicates: False
    validate_certs: False
    hostname: "{{ vc_name }}"
    username: "{{ vc_user }}"
    password: "{{ vc_pass }}"
    datacenter: "{{ dc }}"
    cluster: "{{ cluster_name }}"
    datastore: "{{ datast }}"
    name: "{{ vra_fqdn }}"
    power_on: yes
    ovf: "{{ vra_location }}"
    disk_provisioning: "thin"
    networks: "{u'Network 1':u'{{ pg_mgmt_name }}'}"
    properties:
        "vami.hostname": "{{ vra_fqdn }}"
        "hostname": "{{ vra_fqdn }}"
        "varoot-password": "{{ vra_password }}"
        "va-ssh-enabled": "True"
        "ntp-servers": "{{ vm_ntp }}"
        "fips-mode": "disabled"
        "vami.gateway.VMware_vRealize_Orchestrator_Appliance": "{{ pg_mgmt_gw }}"
        "vami.domain.VMware_vRealize_Orchestrator_Appliance": "{{ vm_domain }}"
        "vami.searchpath.VMware_vRealize_Orchestrator_Appliance": "{{ vm_domain }}"
        "vami.DNS.VMware_vRealize_Orchestrator_Appliance": "{{ vm_dns }}"
        "vami.ip0.VMware_vRealize_Orchestrator_Appliance": "{{ vra_ip }}"
        "vami.netmask0.VMware_vRealize_Orchestrator_Appliance": "{{ pg_mgmt_mask }}"
        "k8s-cluster-cidr": "100.64.0.0/22"
        "k8s-service-cidr": "100.64.4.0/22"
  delegate_to: localhost